const ADMIN_EMAIL = 'ezemaebuka43@gmail.com'
const AUTH_KEY = 'axs-auth-session'
export function getSession() { try { return JSON.parse(sessionStorage.getItem(AUTH_KEY) || 'null') } catch { return null } }
export function isAdminSession() { return getSession()?.email?.toLowerCase() === ADMIN_EMAIL }
export async function requireAuth(onAuthenticated) { const response = await fetch('/api/auth/session'); const data = await response.json(); if (data.user) { sessionStorage.setItem(AUTH_KEY, JSON.stringify(data.user)); if (data.user.approved || data.user.email?.toLowerCase() === ADMIN_EMAIL) return onAuthenticated(data.user); return renderApprovalScreen() } renderAuthScreen() }
export async function renderApprovalScreen() { const root=document.querySelector('#root'); root.innerHTML='<main class="axs-auth-shell"><section class="axs-auth-card"><div class="axs-auth-inner"><h1>Approval required</h1><p>An admin must approve your account before you can continue.</p><button id="axs-check-approval" type="button">Check approval</button></div></section></main>'; document.querySelector('#axs-check-approval').onclick=async()=>{ const status=await fetch('/api/auth/status').then(response=>response.json()); if(status.approved && status.deviceApproved) location.reload(); else if(status.approved) { const device=await fetch('/api/auth/device',{method:'POST'}).then(response=>response.json()); root.querySelector('.axs-auth-inner').innerHTML=`<h1>Device code</h1><p>Ask an admin to approve this device code.</p><div style="font-size:32px;font-weight:800;letter-spacing:8px;padding:24px 0">${device.code}</div><button id="axs-check-device" type="button">Check device approval</button>`; root.querySelector('#axs-check-device').onclick=()=>location.reload() } } }
export async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); sessionStorage.removeItem(AUTH_KEY); location.href = '/signin' }
export function renderAuthScreen() {
 const root=document.querySelector('#root'); if(!root)return
 const style=document.createElement('style'); style.textContent='.axs-auth-inner h1{font-size:clamp(24px,7vw,34px)}.axs-auth-inner label,.axs-auth-inner input,.axs-auth-inner button,.axs-auth-subtitle,.axs-auth-switch{font-size:14px!important}.axs-auth-inner button{min-height:44px}'; document.head.appendChild(style)
 root.innerHTML=`<main class="axs-auth-shell"><section class="axs-auth-brand"><div class="axs-logo">axs</div></section><section class="axs-auth-card"><div class="axs-auth-inner"><h1>Sign in or create account</h1><p class="axs-auth-subtitle">If you don&apos;t have an account, we&apos;ll create one for you.</p><form id="axs-auth-form"><label for="axs-email">Email address</label><input id="axs-email" name="email" type="email" autocomplete="email" required><label id="axs-password-label" for="axs-password">Password</label><input id="axs-password" name="password" type="password" autocomplete="current-password" minlength="8" required><button type="submit">Continue</button><p id="axs-auth-error" role="alert"></p></form><p class="axs-auth-switch">Already have an account? <button id="axs-login-toggle" type="button">Login</button></p></div><footer><a href="/terms">Terms of Use</a><a href="/privacy">Privacy Policy</a></footer></section></main>`
 const form=document.querySelector('#axs-auth-form'), toggle=document.querySelector('#axs-login-toggle'), subtitle=document.querySelector('.axs-auth-subtitle'), error=document.querySelector('#axs-auth-error'); let loginMode=false
 const sync=()=>{subtitle.textContent=loginMode?'Enter your email and password to continue.':"If you don't have an account, we'll create one for you.";toggle.textContent=loginMode?'Create account':'Login'}
 toggle.onclick=()=>{loginMode=!loginMode;sync()}
 form.onsubmit=async event=>{event.preventDefault();error.textContent='';const submit=form.querySelector('button[type="submit"]');if(submit){submit.disabled=true;submit.textContent='Checking...'}try{const data=Object.fromEntries(new FormData(form));let response=await fetch(loginMode?'/api/auth/login':'/api/auth/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});let result=await response.json().catch(()=>({}));if(!response.ok&&result.canLogin&&!loginMode){loginMode=true;sync();response=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});result=await response.json().catch(()=>({}))}if(!response.ok){error.textContent=result.error||'Unable to continue. Please check your details and try again.';return}sessionStorage.setItem(AUTH_KEY,JSON.stringify(result.user));if(result.admin||result.user?.approved){location.href='/';return}await showApprovalFlow()}catch(errorValue){console.error('[v0] auth submit failed',errorValue);error.textContent='Unable to reach the sign-in service. Please refresh and try again.'}finally{if(submit){submit.disabled=false;submit.textContent='Continue'}}}; sync()
 async function showApprovalFlow() { const status = await fetch('/api/auth/status').then(response => response.json()).catch(() => ({})); root.innerHTML=`<main class="axs-auth-shell"><section class="axs-auth-card"><div class="axs-auth-inner"><h1 id="axs-flow-title">Approval required</h1><p id="axs-flow-copy">An admin must approve your account before you can continue.</p><div id="axs-device-code" hidden></div><button id="axs-flow-action" type="button">Check approval</button></div></section></main>`; const title=document.querySelector('#axs-flow-title'), copy=document.querySelector('#axs-flow-copy'), codeBox=document.querySelector('#axs-device-code'), action=document.querySelector('#axs-flow-action'); let current=status; const refresh=async()=>{ current=await fetch('/api/auth/status').then(response=>response.json()).catch(() => current); if (!current.approved) { title.textContent='Approval required'; copy.textContent='An admin must approve your account before you can continue.'; return } if (!current.deviceCode) { const device=await fetch('/api/auth/device',{method:'POST'}).then(response=>response.json()); current.deviceCode=device.code } if (!current.deviceApproved) { title.textContent='Device code'; copy.textContent='Ask an admin to approve this device code.'; codeBox.hidden=false; codeBox.textContent=current.deviceCode; codeBox.style.cssText='font-size:32px;font-weight:800;letter-spacing:8px;padding:24px 0'; return } location.reload() }; action.onclick=refresh; await refresh() }
}
