import { createServer } from 'node:http'
import { readFile } from 'node:fs/promises'
import { extname, join, normalize } from 'node:path'
import { fileURLToPath } from 'node:url'
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto'
import pg from 'pg'

const root = fileURLToPath(new URL('.', import.meta.url))
const port = Number(process.env.PORT || 5173)
const pool = process.env.DATABASE_URL ? new pg.Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } }) : null
const mime = { '.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon' }
const cookie = (req) => Object.fromEntries((req.headers.cookie || '').split(';').filter(Boolean).map(v => v.trim().split('=')))
const json = (res, status, body, headers = {}) => { res.writeHead(status, {'content-type':'application/json; charset=utf-8', ...headers}); res.end(JSON.stringify(body)) }
const hash = (password, salt = randomBytes(16).toString('hex')) => `${salt}:${scryptSync(password, salt, 64).toString('hex')}`
const verify = (password, stored) => { const [salt, value] = String(stored).split(':'); if (!salt || !value) return false; return timingSafeEqual(Buffer.from(value, 'hex'), scryptSync(password, salt, 64)) }
async function ensureAuthTable() { if (pool) { await pool.query('CREATE TABLE IF NOT EXISTS axs_users (id TEXT PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, transfer_limit INTEGER NOT NULL DEFAULT 2, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())'); await pool.query('ALTER TABLE axs_users ADD COLUMN IF NOT EXISTS transfer_limit INTEGER NOT NULL DEFAULT 2'); await pool.query('CREATE TABLE IF NOT EXISTS axs_ticket_transfers (id TEXT PRIMARY KEY, sender_id TEXT NOT NULL REFERENCES axs_users(id), recipient_email TEXT NOT NULL, ticket_id TEXT NOT NULL, event_name TEXT, ticket_name TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())') } }
async function body(req) { let data=''; for await (const chunk of req) data += chunk; return JSON.parse(data || '{}') }
async function authApi(req, res, url) {
  if (!pool) return json(res, 503, { error: 'Authentication database is not configured.' })
  await ensureAuthTable(); const cookies = cookie(req); const sid = cookies.axs_session
  if (url.pathname === '/api/auth/session') { if (!sid) return json(res, 200, { user: null }); const result = await pool.query('SELECT id,email FROM axs_users WHERE id=$1', [sid]); return json(res, 200, { user: result.rows[0] || null }) }
  if (req.method !== 'POST') return json(res, 405, { error: 'Method not allowed' })
  const data = await body(req); const email = String(data.email || '').trim().toLowerCase(); const password = String(data.password || '')
  if (!email || password.length < 8) return json(res, 400, { error: 'Enter a valid email and a password of at least 8 characters.' })
  if (url.pathname === '/api/auth/register') { const id = randomBytes(18).toString('hex'); try { await pool.query('INSERT INTO axs_users (id,email,password_hash) VALUES ($1,$2,$3)', [id,email,hash(password)]); return json(res, 200, { user: { id,email }, admin: email === 'ezemaebuka43@gmail.com' }, {'set-cookie':`axs_session=${id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000`}) } catch { return json(res, 409, { error: 'Unable to create this account.' }) } }
  if (url.pathname === '/api/auth/login') { const result = await pool.query('SELECT id,email,password_hash FROM axs_users WHERE email=$1', [email]); const user = result.rows[0]; if (!user || !verify(password,user.password_hash)) return json(res, 401, { error: 'Invalid email or password.' }); return json(res, 200, { user: { id:user.id,email:user.email }, admin: email === 'ezemaebuka43@gmail.com' }, {'set-cookie':`axs_session=${user.id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000`}) }
  if (url.pathname === '/api/auth/logout') return json(res, 200, {}, {'set-cookie':'axs_session=; Path=/; Max-Age=0'})
  return json(res, 404, { error: 'Not found' })
}
async function ticketmaster(url) { return new Response(JSON.stringify({ _embedded: { events: [] }, events: [], disabled: true, message: 'Live event search is temporarily unavailable.' }), { status: 503, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' } }) }
async function sendTransferEmail(data, userEmail) {
  const recipientEmail = String(data.recipientEmail || '').trim().toLowerCase()
  const eventName = String(data.eventName || 'Your AXS event').trim()
  const ticketName = String(data.ticketName || 'Ticket').trim()
  const ticketId = String(data.ticketId || '').trim()
  if (!/^\\S+@\\S+\\.\\S+$/.test(recipientEmail) || !ticketId) return { status: 400, body: { error: 'A valid recipient email and ticket ID are required.' } }
  if (!process.env.RESEND_API_KEY || !process.env.RESEND_FROM_EMAIL) return { status: 503, body: { error: 'Transfer email is not configured.' } }
  const response = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { authorization: `Bearer ${process.env.RESEND_API_KEY}`, 'content-type': 'application/json' }, body: JSON.stringify({ from: process.env.RESEND_FROM_EMAIL, to: [recipientEmail], subject: `You received a ticket for ${eventName}`, html: `<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#10214a"><h1 style="margin-bottom:8px">AXS ticket transfer</h1><p>You received a ticket from ${userEmail || 'another AXS user'}.</p><div style="padding:20px;background:#f2f5fb;border-radius:16px"><strong>${eventName}</strong><br>${ticketName}<br><small>Ticket reference: ${ticketId}</small></div><p>Sign in to AXS to view your ticket and event details.</p></div>` }))
  if (!response.ok) return { status: 502, body: { error: 'Unable to send the transfer email.' } }
  return { status: 200, body: { sent: true, recipientEmail } }
}
const server = createServer(async (req,res) => { const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`); try { const protectedRoutes = ['/profile','/tickets/create','/claim','/checkout','/manage-tickets','/order-receipt']; if (protectedRoutes.some(route => url.pathname === route || url.pathname.startsWith(`${route}/`))) { const sid = cookie(req).axs_session; if (!sid || !pool) { res.writeHead(302, { location: '/signin' }); return res.end() } const session = await pool.query('SELECT id FROM axs_users WHERE id=$1', [sid]); if (!session.rows[0]) { res.writeHead(302, { location: '/signin' }); return res.end() } } if (url.pathname === '/admin' || url.pathname === '/admin/') { const sid = cookie(req).axs_session; if (!sid || !pool) { res.writeHead(302, { location: '/signin' }); return res.end() } const admin = await pool.query('SELECT email FROM axs_users WHERE id=$1', [sid]); if (admin.rows[0]?.email?.toLowerCase() !== 'ezemaebuka43@gmail.com') { res.writeHead(302, { location: '/' }); return res.end() } } if (url.pathname === '/api/tickets/transfer' && req.method === 'POST') { const sid = cookie(req).axs_session; if (!sid || !pool) return json(res, 401, { error: 'Sign in to transfer a ticket.' }); const session = await pool.query('SELECT email FROM axs_users WHERE id=$1', [sid]); if (!session.rows[0]) return json(res, 401, { error: 'Sign in to transfer a ticket.' }); const result = await sendTransferEmail(await body(req), session.rows[0].email); return json(res, result.status, result.body) } if (url.pathname.startsWith('/api/auth/')) return await authApi(req,res,url); if (url.pathname === '/api/events') { const r=await ticketmaster(url); res.writeHead(r.status,Object.fromEntries(r.headers)); return res.end(await r.text()) } if (url.pathname.startsWith('/api/apps/public/prod/public-settings/by-id/')) return json(res, 200, { id: url.pathname.split('/').pop(), public: true, auth_required: true, name: 'AXS', features: { ticketmaster: false } }); if (url.pathname.startsWith('/api/apps/')) { const pathname = url.pathname.toLowerCase(); if (pathname.includes('event')) { const tm = await ticketmaster(url); const payload = await tm.json(); const events = payload?._embedded?.events || []; return json(res, tm.status, { data: events, entities: events, _embedded: { events } }); } return json(res, 200, { data: [], entities: [] }); } const requested = url.pathname === '/' ? '/index.html' : url.pathname; const filePath=normalize(join(root,requested)); if (!filePath.startsWith(root)) throw new Error('Invalid path'); res.writeHead(200, {'content-type':mime[extname(filePath)] || 'application/octet-stream'}); res.end(await readFile(filePath)) } catch (error) { console.error('[v0] request error',error); if (res.headersSent) return; res.writeHead(404, {'content-type':'text/plain; charset=utf-8'}); res.end('Not found') } })
server.listen(port, () => console.log(`[v0] AXS server listening on ${port}`))
